# Generated by Django 4.0.2 on 2022-02-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('url', models.URLField()),
                ('host', models.URLField()),
                ('displayName', models.TextField()),
                ('github', models.URLField()),
            ],
        ),
    ]
