# Generated by Django 4.0.2 on 2022-02-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.TextField(),
        ),
    ]
