# Generated by Django 4.0.2 on 2022-02-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(),
        ),
    ]
