# Generated by Django 4.0.2 on 2022-02-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_alter_author_host_alter_author_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.TextField(blank=True),
        ),
    ]
