# Generated by Django 4.0.2 on 2022-02-19 21:20

import author.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0010_alter_author_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=author.models.upload_path),
        ),
    ]
