# Generated by Django 4.0.2 on 2022-02-19 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0011_alter_author_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='profileImage',
        ),
    ]
