# Generated by Django 4.0.2 on 2022-02-24 09:11

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
