# Generated by Django 4.0.2 on 2022-02-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_commentssrc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commentsSrc',
        ),
    ]
