# Generated by Django 4.0.2 on 2022-02-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_initial'),
        ('post', '0005_remove_post_commentssrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commentItems',
            field=models.ManyToManyField(blank=True, related_name='post_commentSrc', to='comment.Comment'),
        ),
    ]
