# Generated by Django 4.0.2 on 2022-03-23 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.URLField(blank=True)),
                ('context', models.TextField(default='https://www.w3.org/ns/activitystreams')),
                ('summary', models.TextField(blank=True, null=True)),
                ('type', models.TextField(default='like')),
                ('object', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
